/**
 * T030: ReviewWriter Adapter
 *
 * Converts DesignReviewRecord entity to human-readable markdown review document.
 * Sections: findings by severity, decision conflicts with references, recommendations.
 * Writes to specified output path.
 *
 * Clean Architecture: adapter layer — handles file I/O and markdown formatting.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { DesignReviewRecord, ReviewFinding } from '../../types.js';

export class ReviewWriter {
  async write(record: DesignReviewRecord, outputPath: string): Promise<void> {
    const markdown = formatReviewMarkdown(record);
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, markdown, 'utf-8');
  }
}

// Exported for direct testing without file I/O
export function formatReviewMarkdown(record: DesignReviewRecord): string {
  const lines: string[] = [];

  lines.push('# Design Review');
  lines.push('');
  lines.push(`**Artifact:** ${record.reviewedArtifact}`);
  lines.push(`**Date:** ${record.timestamp}`);
  lines.push(`**Participants:** ${record.participants.join(', ')}`);
  lines.push(`**Status:** ${formatApprovalStatus(record.approvalStatus)}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(record.summary);
  lines.push('');

  if (record.findings.length === 0) {
    lines.push('## Findings');
    lines.push('');
    lines.push('No findings detected. Tasks are ready for implementation.');
    lines.push('');
  } else {
    // Group by severity
    const high = record.findings.filter((f) => f.severity === 'high');
    const medium = record.findings.filter((f) => f.severity === 'medium');
    const low = record.findings.filter((f) => f.severity === 'low');

    if (high.length > 0) {
      lines.push('## 🔴 High Severity');
      lines.push('');
      for (const f of high) {
        lines.push(...formatFinding(f));
      }
    }

    if (medium.length > 0) {
      lines.push('## 🟡 Medium Severity');
      lines.push('');
      for (const f of medium) {
        lines.push(...formatFinding(f));
      }
    }

    if (low.length > 0) {
      lines.push('## 🟢 Low Severity');
      lines.push('');
      for (const f of low) {
        lines.push(...formatFinding(f));
      }
    }

    // Decision conflicts section
    const conflicts = record.findings.filter(
      (f) => f.type === 'decision_conflict',
    );
    if (conflicts.length > 0) {
      lines.push('## Decision Conflicts');
      lines.push('');
      for (const c of conflicts) {
        lines.push(`- **${c.description}**`);
        lines.push(`  - Reference: ${c.reference}`);
        lines.push(`  - Action: ${c.recommendation}`);
        lines.push('');
      }
    }

    // Recommendations
    lines.push('## Recommendations');
    lines.push('');
    for (const f of record.findings) {
      lines.push(`- ${f.recommendation}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Squad-SpecKit Bridge*');
  lines.push('');

  return lines.join('\n');
}

function formatFinding(finding: ReviewFinding): string[] {
  return [
    `### ${finding.type}: ${finding.description}`,
    '',
    `- **Type:** ${finding.type}`,
    `- **Reference:** ${finding.reference}`,
    `- **Recommendation:** ${finding.recommendation}`,
    '',
  ];
}

function formatApprovalStatus(status: string): string {
  switch (status) {
    case 'approved':
      return '✅ Approved';
    case 'changes_requested':
      return '⚠️ Changes Requested';
    case 'blocked':
      return '🚫 Blocked';
    default:
      return status;
  }
}
