/**
 * T030 Tests: ReviewWriter Adapter
 *
 * Tests the markdown formatting output (pure function test)
 * and file writing (integration test with temp dir).
 */

import { describe, it, expect, afterEach } from 'vitest';
import { formatReviewMarkdown } from '../../src/review/adapters/review-writer.js';
import { ReviewWriter } from '../../src/review/adapters/review-writer.js';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { readFile, rm, mkdtemp } from 'node:fs/promises';
import type { DesignReviewRecord } from '../../src/types.js';

function makeRecord(
  overrides: Partial<DesignReviewRecord> = {},
): DesignReviewRecord {
  return {
    reviewedArtifact: 'specs/001/tasks.md',
    timestamp: '2025-07-25T10:00:00.000Z',
    participants: ['bridge-cli'],
    findings: [],
    approvalStatus: 'approved',
    summary: 'Reviewed 5 tasks. No findings detected.',
    ...overrides,
  };
}

describe('formatReviewMarkdown', () => {
  it('produces valid markdown with header and summary', () => {
    const md = formatReviewMarkdown(makeRecord());

    expect(md).toContain('# Design Review');
    expect(md).toContain('**Artifact:** specs/001/tasks.md');
    expect(md).toContain('**Status:** ✅ Approved');
    expect(md).toContain('## Summary');
    expect(md).toContain('No findings detected');
  });

  it('groups findings by severity', () => {
    const record = makeRecord({
      approvalStatus: 'blocked',
      findings: [
        {
          type: 'ordering',
          severity: 'high',
          description: 'Missing dependency T999',
          reference: 'Task T005',
          recommendation: 'Add T999',
        },
        {
          type: 'decision_conflict',
          severity: 'medium',
          description: 'Conflicts with JWT decision',
          reference: 'Decision: Use JWT',
          recommendation: 'Review alignment',
        },
        {
          type: 'scope',
          severity: 'low',
          description: 'Underspecified task',
          reference: 'Task T099',
          recommendation: 'Add details',
        },
      ],
    });

    const md = formatReviewMarkdown(record);

    expect(md).toContain('## 🔴 High Severity');
    expect(md).toContain('## 🟡 Medium Severity');
    expect(md).toContain('## 🟢 Low Severity');
    expect(md).toContain('## Decision Conflicts');
    expect(md).toContain('## Recommendations');
    expect(md).toContain('**Status:** 🚫 Blocked');
  });

  it('includes decision conflict details', () => {
    const record = makeRecord({
      approvalStatus: 'changes_requested',
      findings: [
        {
          type: 'decision_conflict',
          severity: 'medium',
          description: 'Task T010 may conflict with JWT decision',
          reference: 'Decision: Use JWT authentication',
          recommendation: 'Review alignment before proceeding',
        },
      ],
    });

    const md = formatReviewMarkdown(record);

    expect(md).toContain('Decision Conflicts');
    expect(md).toContain('Use JWT authentication');
    expect(md).toContain('⚠️ Changes Requested');
  });

  it('shows recommendations list', () => {
    const record = makeRecord({
      findings: [
        {
          type: 'risk',
          severity: 'low',
          description: 'Risk area',
          reference: 'ref',
          recommendation: 'Consult agent expertise',
        },
      ],
    });

    const md = formatReviewMarkdown(record);

    expect(md).toContain('## Recommendations');
    expect(md).toContain('- Consult agent expertise');
  });

  it('includes generator attribution', () => {
    const md = formatReviewMarkdown(makeRecord());
    expect(md).toContain('Generated by Squad-SpecKit Bridge');
  });
});

describe('ReviewWriter (file I/O)', () => {
  let tempDir: string;

  afterEach(async () => {
    if (tempDir) {
      await rm(tempDir, { recursive: true, force: true });
    }
  });

  it('writes review markdown to file', async () => {
    tempDir = await mkdtemp(join(tmpdir(), 'review-writer-'));
    const outputPath = join(tempDir, 'review.md');
    const writer = new ReviewWriter();

    await writer.write(makeRecord(), outputPath);

    const content = await readFile(outputPath, 'utf-8');
    expect(content).toContain('# Design Review');
    expect(content).toContain('specs/001/tasks.md');
  });

  it('creates parent directories if missing', async () => {
    tempDir = await mkdtemp(join(tmpdir(), 'review-writer-'));
    const outputPath = join(tempDir, 'nested', 'dir', 'review.md');
    const writer = new ReviewWriter();

    await writer.write(makeRecord(), outputPath);

    const content = await readFile(outputPath, 'utf-8');
    expect(content).toContain('# Design Review');
  });
});
