/**
 * T005 tests: generateLearningsMarkdown()
 */

import { describe, it, expect } from 'vitest';
import {
  generateLearningsMarkdown,
  type ExtractedReverseLearning,
  type LearningsMetadata,
} from '../../src/types.js';

const baseMetadata: LearningsMetadata = {
  featureName: 'Knowledge Feedback Loop',
  specId: '009-knowledge-feedback-loop',
  executionPeriod: { start: '2026-03-23', end: '2026-03-25' },
  agents: ['gilfoyle', 'dinesh', 'jared'],
};

function makeEntry(overrides: Partial<ExtractedReverseLearning> = {}): ExtractedReverseLearning {
  return {
    title: 'Test Learning',
    content: 'Some content body',
    sourceType: 'histories',
    attribution: 'gilfoyle',
    timestamp: '2026-03-24',
    fingerprint: 'fp_test123',
    classification: 'learnings-only',
    category: 'architectural-insights',
    ...overrides,
  };
}

describe('generateLearningsMarkdown', () => {
  it('generates correct header with feature name and spec id', () => {
    const entries = [makeEntry()];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('# Implementation Learnings — Knowledge Feedback Loop');
    expect(md).toContain('**Spec**: 009-knowledge-feedback-loop');
    expect(md).toContain('**Execution Period**: 2026-03-23 to 2026-03-25');
    expect(md).toContain('**Agents**: gilfoyle, dinesh, jared');
  });

  it('includes YAML frontmatter', () => {
    const entries = [makeEntry()];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toMatch(/^---\n/);
    expect(md).toContain('spec_id: 009-knowledge-feedback-loop');
    expect(md).toContain('sync_generation: 1');
    expect(md).toContain('total_learnings: 1');
  });

  it('groups entries by category', () => {
    const entries = [
      makeEntry({ category: 'architectural-insights', title: 'Arch 1' }),
      makeEntry({ category: 'risks', title: 'Risk 1' }),
      makeEntry({ category: 'decisions', title: 'Decision 1' }),
    ];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('## Architectural Insights');
    expect(md).toContain('## Risks Encountered');
    expect(md).toContain('## Decisions Made During Implementation');
  });

  it('omits empty categories', () => {
    const entries = [makeEntry({ category: 'risks', title: 'Risk Only' })];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('## Risks Encountered');
    expect(md).not.toContain('## Architectural Insights');
    expect(md).not.toContain('## Integration Patterns');
    expect(md).not.toContain('## Performance Notes');
    expect(md).not.toContain('## Decisions Made During Implementation');
    expect(md).not.toContain('## Reusable Techniques');
  });

  it('includes metadata footer', () => {
    const entries = [makeEntry()];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('_Generated by `squask sync-reverse`');
    expect(md).toContain('.bridge-sync-reverse.json');
  });

  it('renders multiple entries in one category correctly', () => {
    const entries = [
      makeEntry({ title: 'First Insight', content: 'Content A', attribution: 'gilfoyle' }),
      makeEntry({ title: 'Second Insight', content: 'Content B', attribution: 'dinesh' }),
    ];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('### First Insight');
    expect(md).toContain('### Second Insight');
    expect(md).toContain('_Source: gilfoyle (history) | 2026-03-24_');
    expect(md).toContain('_Source: dinesh (history) | 2026-03-24_');
    expect(md).toContain('Content A');
    expect(md).toContain('Content B');
  });

  it('renders source types correctly (history, decision, skill)', () => {
    const entries = [
      makeEntry({ sourceType: 'histories', attribution: 'gilfoyle', title: 'H' }),
      makeEntry({ sourceType: 'decisions', attribution: 'team', title: 'D' }),
      makeEntry({ sourceType: 'skills', attribution: 'bridge', title: 'S', category: 'reusable-techniques' }),
    ];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('(history)');
    expect(md).toContain('(decision)');
    expect(md).toContain('(skill)');
  });

  it('truncates content longer than 500 chars', () => {
    const longContent = 'x'.repeat(600);
    const entries = [makeEntry({ content: longContent })];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('[...]');
    expect(md).not.toContain('x'.repeat(600));
  });

  it('counts sources in frontmatter', () => {
    const entries = [
      makeEntry({ sourceType: 'histories' }),
      makeEntry({ sourceType: 'histories', title: 'H2' }),
      makeEntry({ sourceType: 'decisions', title: 'D1', category: 'decisions' }),
    ];
    const md = generateLearningsMarkdown(entries, baseMetadata);

    expect(md).toContain('histories: 2');
    expect(md).toContain('decisions: 1');
    expect(md).toContain('skills: 0');
    expect(md).toContain('total_learnings: 3');
  });

  it('returns valid markdown for empty entries list', () => {
    const md = generateLearningsMarkdown([], baseMetadata);

    expect(md).toContain('# Implementation Learnings');
    expect(md).toContain('total_learnings: 0');
    expect(md).not.toContain('## Architectural Insights');
  });
});
